### ISSUE TITLE
Error when opening 81x files

### ISSUE THREAD

**Issue by plfb097** [bgctw/RespChamberProc#5]
Hi, 

I'm hoping you can help me understand and fix and error that I am repeatedly getting when trying to open 81x files using read81xVar. I have previously read in 81x files fine, however for the last few months of files, I am getting this message: 

Error in `bind_rows()`:
! Can't combine `..1$Tcham` <character> and `..5$Tcham` <double>.

Do you have any idea how this can be fixed? 

Help much appreciated, thank you.

**Comment by bgctw** [comment]
The format of the files might have changed. Can you, please, provide access to your file (link to some upload) so that I have a chance to debug. However, I cannot promise to have a look into it soon.

**Comment by plfb097** [comment]
Thanks for your quick response, here's access to the file:

https://www.dropbox.com/scl/fi/b05vv9fgt6zy5qwzj974c/TG10-01350-202327500.81x?rlkey=8u00qczmzck4hiir08stm69t1&dl=0

Any help is very much appreciated, thank you!

**Comment by bgctw** [comment]
The provided file has a strange row 213, where the Temperature column holds value " Chamber close not detected - Port: 14, Observation: 1 ". This is currently not handled well by RespChamberProc. It detects column type character rather than numeric. This, in turn, causes subsequent errors on merging different chunks of data, that have now different types.

I will have a look if I can adapt RespChamberProc to rely on the Type column to remove those erroneous lines and reparse the other lines.

**Comment by bgctw** [comment]
Please, try reading your file with the package installed from recent master branch. 

Remark:  The temperature numbers in your example file seem unreasonably high for what I have seen from respiration chambers.

**Comment by plfb097** [comment]
That's worked now- that's so helpful thank you very much

**Comment by bgctw** [comment]
Welcome - The package gets better because of your help of spotting the problems.
